### PR TITLE
Fix "Show products from subcategories"

### PR DESCRIPTION
**Pull request by mcdado**
Fixes a problematic behavior reported at https://github.com/PrestaShop/blocklayered/pull/99

### CODE REVIEW

**Comment by mcdado** [comment]
@geedamed check if this works for you.

**Comment by mcdado** [comment]
Also @rez0n

**Comment by Danoosh** [comment]
When there's no filter selected and we enter in a category all of them applies filters. Why when there's no filters selected by users it should apply filters? Although the contents does not change but it's still inappropriate.

**Comment by Danoosh** [comment]
@mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Comment by mcdado** [comment]
> @mcdado Can you please check [this change](https://github.com/iPresta/blocklayered/commit/188ff79c279bacd245b92d766db7d88100d70713) works for category sorting that you want or not?

I tested it and it works well. I close this PR in favor of https://github.com/PrestaShop/blocklayered/pull/122

**Pull request closed without merging**
