### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Denys06**
How does the fact that in my version (the latest) the order of filters back each time in the default order when I want to edit and change?

Before save
bug2

After save when I edit :
bug

I have to put them in the right order each time you change the filters. How can I resolve this bug please?

### CODE REVIEW

**Comment by Denys06** [comment]
Hello,

I still have the problem I have indicated to you in screenshoot.
Do you please have a solution to fix my problem?

Cordially
Denys

**Comment by Denys06** [comment]
Do you have any idea why my request was closed?

**Comment by jeromenadaud** [comment]
Hi, it was close by merging dev into master branch.
Sorry, for the inconvenience.

Best regards

**Comment by Denys06** [comment]
Thank you for your reply

 Do you know if a solution was found, because I did not find a change that could come solve my problem?

**Pull request closed without merging**
