### PR TITLE
[-] MO : Disable cache because temp tables always changes (PNM-3587)

### PR DESCRIPTION
**Pull request by jocel1**

### CODE REVIEW

**Comment by carras** [comment]
This seems to solve the problem of using cache with blocklayered describe:

http://forge.prestashop.com/browse/NM-574
AND
http://forge.prestashop.com/browse/PNM-3587

**Comment by 1lukaszj** [comment]
Hi,
when I used the updated blocklayered.php file it seems to me that the filtering does not work when cache is switched off. The filtering keeps running without displaying the end result.

**Comment by zeidlos** [comment]
How do we get this into the release? I had to hotfix it on the server directly, but that's not really cool.
Props to jocel1 for fixing it. Thanks. :)

**Comment by htrex** [comment]
yes please, this is still not merged in PS 1.6.1.5 and without it the blocklayered module is severely broken, thanks!

**Comment by htrex** [comment]
I've upgraded PS to version 1.6.1.6 and had to reapply the patch manually again as the one click update broke the blocklayered module again when the standard PS file system caching is active. 
@jocel1 can you please check what's the problem with this patch not being merged to trunk?

**Comment by axisepm** [comment]
Hi, I applied this patch manually to an 1.6.1.5 install an even when it fixed the problem with the cache reloading the same categories all over the place, it is wreaking havoc on the BO. Many times changes applied to products don't persist. The problems I saw were mainly on features edition and qty management. To fix I had to advance to 1.6.1.6 (so blocklayered.php remained unaltered) to elude the BO issue, and change from APC to xCache to get rid of the initial problem. I think this PR needs more testing.

**Comment by htrex** [comment]
This problem is about 1 year hold, any word from the main dev team?

**Comment by axisepm** [comment]
@jocel1 any news on this? This is blocking use of APC cache in prestashop, at least in my instance.

**Comment by jocel1** [comment]
I saw blocklayered was tag 2.2.0 6 days ago, hopefully it will be integrated in the next release

**Comment by legovini** [comment]
I tried to manually apply this patch to PrestaShop 1.6.1.1, but what happens now when the cache is enabled is that the pages following the first appear empty, while they're populated with products when the cache is disabled. Do you have any suggestion about how to fix this older PrestaShop version?

**Comment by kintaro1981** [comment]
I cant understand if this is fixed or not (and in which version).

**Comment by maximebiloe** [comment]
Hello @kintaro1981,

It's available since `2.2.0` version.

Regards

**Pull request merged**
